# Generated by Django 2.0.3 on 2020-09-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('pw', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=64)),
                ('Lng', models.FloatField()),
                ('Lat', models.FloatField()),
                ('tradeTime', models.CharField(max_length=64)),
                ('totalPrice', models.FloatField()),
                ('price', models.FloatField()),
                ('square', models.FloatField()),
                ('bedRoom', models.IntegerField()),
                ('livingRoom', models.IntegerField()),
                ('kitchen', models.IntegerField()),
                ('bathRoom', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('buildingType', models.IntegerField()),
                ('constructionTime', models.CharField(max_length=64)),
                ('renovationCondition', models.IntegerField()),
                ('buildingStructure', models.IntegerField()),
                ('ladderRatio', models.FloatField()),
                ('elevator', models.IntegerField()),
                ('fiveYearsProperty', models.IntegerField()),
                ('subway', models.IntegerField()),
                ('district', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Predict_house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lng', models.FloatField()),
                ('Lat', models.FloatField()),
                ('tradeTime', models.CharField(max_length=64)),
                ('totalPrice', models.FloatField()),
                ('price', models.FloatField()),
                ('square', models.FloatField()),
                ('bedRoom', models.IntegerField()),
                ('livingRoom', models.IntegerField()),
                ('kitchen', models.IntegerField()),
                ('bathRoom', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('buildingType', models.IntegerField()),
                ('renovationCondition', models.IntegerField()),
                ('buildingStructure', models.IntegerField()),
                ('ladderRatio', models.FloatField()),
                ('elevator', models.IntegerField()),
                ('fiveYearsProperty', models.IntegerField()),
                ('subway', models.IntegerField()),
                ('district', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='acc_user',
            name='predict',
            field=models.ManyToManyField(blank=True, related_name='user', to='login.Predict_house'),
        ),
        migrations.AddField(
            model_name='acc_user',
            name='search',
            field=models.ManyToManyField(blank=True, related_name='user', to='login.House'),
        ),
    ]
